name: CTF PLugin
version: 2.3.0
api: 1.13.0
main: Plugins\game\ctf\CTFPlugIn
author: EnchantedSkulls
authors: [EnchantedSkulls]
description: EnchantedSkulls Minigame [Capture-The-Flag] 
website: http://www.youtube.com/user/EnchantedSkulls
commands:
 ctf:
  description: "Start EnchantedSkulls Minigame Capture-The-Flag"
  permission: EnchantedSkulls.ctf
permissions:
  EnchantedSkulls.ctf:
    description: "Catpure The Flag Mini-game Plugin"
    default: true
    children:
      EnchantedSkulls.ctf.command:
        description: "Allows use all CTF commands."
        default: true
        children:
          EnchantedSkulls.ctf.command.home:
            description: "Allow use of [home] command"
            default: true
          mcg76.ctf.command.start:
            description: "Allows use of [start]commands"
            default: true            
          mcg76.ctf.command.stop:
            description: "Allows use of [stop] commands"
            default: true
          mcg76.ctf.command.leave:
            description: "Allows use of [leave] commands" 
            default: true           
          mcg76.ctf.command.create:
            description: "Allows use of [create] commands"            
            default: op            
          mcg76.ctf.command.reset:
            description: "Allows use of [reset] commands"
            default: op                                    
          mcg76.ctf.command.stats:
            description: "Allows use of [stats] commands"                                               
            default: true 
          mcg76.ctf.command.joinblue:
            description: "Allows use of [jointeamblue] commands."
            default: true
          mcg76.ctf.command.blockon:
            description: "Allows use of [blockon] commands"                                               
            default: true 
          mcg76.ctf.command.blockoff:
            description: "Allows use of [blockoff] commands."
            default: false			
          mcg76.ctf.command.joinred:
            description: "Allows use of [jointeamred] commands."
            default: Spectator	
          mcg76.ctf.command.setblue:
            description: "Allows use of [setteamblue commands."
            default: Spectator			
          mcg76.ctf.command.setred:
            description: "Allows use of [setteamred] commands."
            default: Spectator	      
          mcg76.ctf.command.setnew:
            description: "Allows use of [setsignnew] commands."
            default: Spectator			
          mcg76.ctf.command.setstat:
            description: "Allows use of [setsignstat] commands."
            default: Spectator                       
